### ISSUE TITLE
Limit to one host?

### ISSUE THREAD

**Issue by skornehl** [hiddentao/ansijet#13]
Hi,

for rolling deploys it is necessary for me to be able to pass the host limit and extra vars, sometimes maybe also tags. Am I missing something or is it not possible to do so with anijet (GUI and API)?

Thanks,
Sebastian

**Comment by hiddentao** [comment]
Hmm, at the moment it is not possible to extra vars to the command-line executed by Ansijet. It assumes everything it needs is in the host file. This would be a feature request for a future version.
