### ISSUE TITLE
Error: in production

### ISSUE THREAD

**Issue by kaji-bikash** [hiddentao/ansijet#9]
System: 
   Ubuntu 14.04
   NodeJS v0.11.14

`NODE_ENV=production ./start-app.js` emits 

Error:

```
at ChildProcess.<anonymous> (/home/ubuntu/ansijet/src/support/exec-then.js:105:17)
at ChildProcess.emit (events.js:110:17)
at maybeClose (child_process.js:1000:16)
at Socket.<anonymous> (child_process.js:1168:11)
at Socket.emit (events.js:107:17)
at Pipe.close (net.js:461:12)
```

**Comment by adenot** [comment]
I'm having the same problem when using Nodejs v0.11.14.
After downgrading to v0.11.2, the error now is: 

```
Error: Module not found: application
    at Object.loader.load (/opt/ansijet/node_modules/waigo/src/loader.js:283:11)
    at /opt/ansijet/start-app.js:30:15
    at GeneratorFunctionPrototype.next (native)
    at next (/opt/ansijet/node_modules/co/index.js:83:21)
    at /opt/ansijet/node_modules/co/index.js:102:18
    at processImmediate [as _immediateCallback] (timers.js:317:15)
```

**Comment by hiddentao** [comment]
Will look at this tomorrow.

**Comment by hiddentao** [comment]
So far I'm not seeing any problems with Node 0.11.13, but that's on OS X. Am investigating Ubuntu 11.04x64 now.

**Comment by kaji-bikash** [comment]
I hope it's going to be much more useful it you are to test it with LTS releases preferably Ubuntu 14.04 Trusty

**Comment by hiddentao** [comment]
Sorry, meant to say 14.04x64

**Comment by hiddentao** [comment]
I'm pretty sure that error means that the `ansible-playbook` binary cannot be found.

**Comment by hiddentao** [comment]
I didn't realise that `which xxx` returns a non-zero error code if the executable can't be found. I'm coding in a better error message now. I'm also going to upgrade to the latest release of `waigo-mongo` which supports authentication.

**Comment by hiddentao** [comment]
Ok, now have ansijet up and running on Ubuntu 14.04x64 with Node 0.11.13. So I think this bug was definitely caused by a lack of an `ansible-playbook` binary. Follow the instructions at http://docs.ansible.com/intro_installation.html#latest-releases-via-apt-ubuntu to get that sorted out.
